apiVersion: v1
kind: Service
metadata:
  name: world
  namespace: fdefault
spec:
  ports:
    - name: http-simple-world
      port: 8080
  selector:
    app: simple-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-world
  namespace: fdefault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-world
  template:
    metadata:
      # annotations:
      #   instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: simple-world
        jvm: "true"
    spec:
      containers:
        - name: simple-world
          image: $ACCOUNT_ID.dkr.ecr.$TF_VAR_region.amazonaws.com/cloudwatch-poc-world:$APP_VERSION
          imagePullPolicy: Always
          env:
            - name: MSK_BOOTSTRAP_ADDRESSES
              value: $MSK_BOOTSTRAP_ADDRESSES
            - name: REDIS_PROTOCOL
              value: "rediss"
            - name: REDIS_HOST
              value: $REDIS_ENDPOINT
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_USER
              value: $REDIS_USER
            - name: REDIS_PASS
              value: $REDIS_PASSWORD
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://adot-collector-collector.observability:4317
            - name: AWS_JMX_EXPORTER_METRICS_ENDPOINT
              value: http://adot-collector-collector.observability:4317
            - name: OTEL_PROPAGATORS
              value: tracecontext,baggage,xray
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=app-world"
            - name: OTEL_JMX_TARGET_SYSTEM
              value: "jvm"
            - name: AWS_JMX_ENABLED
              value: "true"
            - name: AWS_REGION
              value: $TF_VAR_region
            - name: AWS_ACCESS_KEY_ID
              value: $AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              value: $AWS_SECRET_ACCESS_KEY
          command:
            - sh
            - "/app/start-docker.sh"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 250m
              memory: 512Mi