apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  ports:
    - name: http-simple-hello
      port: 8080
  selector:
    app: simple-hello

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-hello
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-hello
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: simple-hello
    spec:
      containers:
        - name: simple-hello
          image: $ACCOUNT_ID.dkr.ecr.$TF_VAR_region.amazonaws.com/cloudwatch-poc-hello:$APP_VERSION
          imagePullPolicy: Always
          env:
            - name: MSK_BOOTSTRAP_ADDRESSES
              value: $MSK_BOOTSTRAP_ADDRESSES
          command:
            - sh
            - /app/start-docker.sh
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 250m
              memory: 512Mi